server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
      
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: evenement-service-route
          uri: lb://EVENEMENT
          predicates:
            - Path=/evenements/**
        - id: user-service-route
          uri: lb://USERS-MICROSERVICES
          predicates:
            - Path=/users/**
      #default-filters:
       # - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
            
            

     